<?php
require '/var/www/html/vendor/autoload.php';
define('LARAVEL_START', microtime(true));
$app = require_once '/var/www/html/bootstrap/app.php';

$kernelHttp = $app->make(Illuminate\Contracts\Http\Kernel::class);
$kernelHttp->bootstrap();

// THE REAL ISSUE: my kernel requests get 302 (auth fail) while REAL curl request
// gets 200. => The auth guard works with real requests. So in-kernel flow is not
// representative. The REAL flow rotates sid on GET create (2 Set-Cookie headers),
// and curl's jar holds the LAST cookie. The form token was generated by session
// BEFORE rotation => token belongs to FIRST sid. But the page token we verified:
// GET via curl returned token; and redis session for sid jar-contained has SAME
// token (proven: sid acm1... token 8WVR...). So POST should pass.

// One remaining difference: nginx POST /anggota passes fastcgi. Let's add a debug
// log INSIDE PreventRequestForgery? Modifying vendor is temporary - add try:
// Log the session token and provided token at runtime via a custom middleware
// appended to web group in bootstrap/app.php.

$code = file_get_contents('/var/www/html/bootstrap/app.php');
echo 'has custom mw: ' . var_export(str_contains($code, 'DebugTokens'), true) . "\n";